<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Migrator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\CommonConfiguration\CommonConfiguration.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
